# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-04-09 08:31
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('salutation', models.CharField(default='', max_length=30)),
                ('title', models.CharField(default='', max_length=30)),
                ('phone', models.CharField(default='', max_length=30)),
                ('fax', models.CharField(default='', max_length=30)),
                ('mobile', models.CharField(default='', max_length=30)),
                ('birthday', models.DateField(default='')),
                ('departement', models.CharField(default='', max_length=50)),
                ('rank', models.CharField(default='', max_length=50)),
                ('activity', models.CharField(default='', max_length=50)),
                ('institute', models.CharField(default='', max_length=50)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
