# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-04-09 08:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('benutzeraccounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='birthday',
            field=models.DateField(default='', null=True),
        ),
    ]
