# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-04-09 08:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('benutzeraccounts', '0002_auto_20180409_1046'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='birthday',
            field=models.CharField(default='', max_length=30),
        ),
    ]
