# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-04-09 09:10
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('benutzeraccounts', '0004_auto_20180409_1110'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='phone_number',
            new_name='phone',
        ),
    ]
